### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by griffins** [webinarium/linode-api#1]
Id love to use you library, are there any docs, id love to read docs than source code?

**Comment by webinarium** [comment]
Sorry, this library is under progress, it's not even completed - so you cannot use it. The purpose of this library is to address Linode API v4, that is on the way, too (please see the following quote from the Linode's website):
> This API is an Early Access release. As such, we will be making regular revisions, some of which will contain breaking changes.

I would recommend to use Linode API v3 for now, which is well documented at https://www.linode.com/api. Also, there is another PHP library to wrap this API - https://github.com/webinarium/linode-api3.

When the library for API v4 is ready, I will post a comment here.

**Comment by webinarium** [comment]
Just FYI - the first stable version of the new library has been released.
