### ISSUE TITLE
Composer installation instructions don't work

### ISSUE THREAD

**Issue by leximayfield** [webinarium/linode-api#2]
```
$ composer require "webinarium/linode-api"
```

This doesn't work.  Trying to run this results in an error message:

```
[InvalidArgumentException]
Could not find package webinarium/linode-api.
```

I can't seem to find this library in [Packagist](https://packagist.org) either...

**Comment by leximayfield** [comment]
I notice in #1 you mention that the library might not be ready for prime time.  You might want to mention this fact in the **README.md** file...

**Comment by webinarium** [comment]
I have updated the README as you suggested. Thank you.

**Comment by webinarium** [comment]
Just FYI - the first stable version of the new library has been released.
